### ISSUE TITLE
Support PowerShell core in Ubuntu images.

### ISSUE THREAD

**Issue by lfshr** [Microsoft/vsts-agent-docker#187]
Trying to build out a job using the PowerShell task on the latest ubuntu-16.04 tagged docker container and getting the following error:
```
##[error]Unable to locate executable file: 'pwsh'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

Task is the following:
```
- task: PowerShell@2
  name: customPowershell
  inputs:
    filePath: 'customPowershell.ps1'
```
